/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class preprocess_EncryptNativeC */

#ifndef _Included_preprocess_EncryptNativeC
#define _Included_preprocess_EncryptNativeC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     preprocess_EncryptNativeC
 * Method:    encrypt_vec_to_file
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_preprocess_EncryptNativeC_encrypt_1vec_1to_1file
  (JNIEnv *, jobject, jint, jstring, jstring, jstring);

/*
 * Class:     preprocess_EncryptNativeC
 * Method:    read_encrypt_vec_from_file_comp_inter_sec_prod
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_preprocess_EncryptNativeC_read_1encrypt_1vec_1from_1file_1comp_1inter_1sec_1prod
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     preprocess_EncryptNativeC
 * Method:    read_decrypt_mul_encrypt_write_encrypted_rand_prod
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_preprocess_EncryptNativeC_read_1decrypt_1mul_1encrypt_1write_1encrypted_1rand_1prod
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     preprocess_EncryptNativeC
 * Method:    derandomize_encr_encr_sim_prod
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_preprocess_EncryptNativeC_derandomize_1encr_1encr_1sim_1prod
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     preprocess_EncryptNativeC
 * Method:    decrypt_sim_score
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_preprocess_EncryptNativeC_decrypt_1sim_1score
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
